[package]
name = "markdownfs"
version = "0.0.1"
authors = ["Zack M. Davis <code@zackmdavis.net>"]

[dependencies]
fuse = { git = "https://github.com/zackmdavis/rust-fuse.git", branch = "debug_trait" }
libc = "0.2"
log = "0.3"
markdown = "0.1"
time = "0.1"
